# Generated by Django 3.2 on 2021-10-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_weather', '0002_city_searche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='searche',
            new_name='searched',
        ),
    ]
